spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          secret: my-ultra-secret-key-that-is-at-least-32-bytes-long!
          issuer-uri: https://issuer.example.com
      client:
        registration:
          google:
            client-id: YOUR_CLIENT_ID
            client-secret: YOUR_CLIENT_SECRET
            scope:
              - openid
              - profile
              - email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"